experiment:
  file: './data/input/DataOfExperiment-mmhr.txt'
  diameter: 20
  inflow: 'A-IN mm/hr'
  outflow: 'A-OUT mm/hr'
  lag: '2min' # lags with respect to the simulation
  direction: 'forward' #lag direction, 'forward' or 'backward'
  rain_events: './data/input/RainEventsEXP.csv'

simulation:
  lid.name: "valec_01"
  file: './data/input/sgs_valec_01_jp.inp'
  headers: ['DateTime', 'ElapsedTimeHours'
                                    , 'TotalInflow_mm/hr', 'TotalEvap_mm/hr'
                                    , 'SurfaceInfill_mm/hr', 'PavementPerc_mm/hr'
                                    , 'SoilPerc_mm/hr', 'StorageExfil_mm/hr'
                                    , 'SurfaceRunoff_mm/hr', 'DrainOutflow_mm/hr'
                                    , 'SurfaceLevel_mm', 'PavementLevel_mm'
                                    , 'SoilMoistureContent', 'StorageLevel_mm']

  inflow_mm_hr: 'TotalInflow_mm/hr'      
  outflow_mm_hr: 'DrainOutflow_mm/hr'  

param_grid:
  soil.porosity: [0.5]
  soil.field_capacity: [0.2, 0.4]
  soil.k_saturated: [306]
  soil.k_slope: [45]
  soil.suction_head: [3]
  surface.void_fraction: [0.025]
  storage.void_fraction: [0.3]
  storage.clog_factor: [0]

calibration_mode:
  rain_event: True
  all: False

metrics: ['nse_inflow', 'nse_outflow'
          , 'volume_inflow_sim', 'volume_outflow_sim'
          , 'volume_inflow_exp', 'volume_outflow_exp'
          , 'peak_flow', 'time_peak', 'pbias', 'sd', 'ad', 'qd' ]