experiment:
  file: './data/input/DataOfExperiment-mmhr.txt'
  diameter: 20
  inflow: 'A-IN mm/hr'
  outflow: 'A-OUT mm/hr'
  lag: '1min' # lags with respect to the simulation
  direction: 'forward' #lag direction, 'forward' or 'backward'
  rain_events: './data/input/RainEventsEXP.csv'

simulation:
  lid.name: "UCEEB-VPR1"
  file: './data/input/UCEEB_01.inp'
  headers: ['DateTime', 'ElapsedTimeHours'
                                    , 'TotalInflow_mm/hr', 'TotalEvap_mm/hr'
                                    , 'SurfaceInfill_mm/hr', 'PavementPerc_mm/hr'
                                    , 'SoilPerc_mm/hr', 'StorageExfil_mm/hr'
                                    , 'SurfaceRunoff_mm/hr', 'DrainOutflow_mm/hr'
                                    , 'SurfaceLevel_mm', 'PavementLevel_mm'
                                    , 'SoilMoistureContent', 'StorageLevel_mm']

  inflow_mm_hr: 'TotalInflow_mm/hr'      
  outflow_mm_hr: 'SurfaceLevel_mm'  

param_grid:
  # Drain
  drain.coefficient: [0]
  drain.exponent: [0]
  drain.offset: [0]
  drain.delay: [0]
  
  #DrainMat
  drainmat.thickness: [2]
  drainmat.void_fraction: [0.5]
  drainmat.roughness: [0]

  # Pavement
  pavement.thickness: [0]
  pavement.void_fraction: [0]
  pavement.impervious_fraction: [0]
  pavement.k_saturated: [0]
  pavement.clog_factor: [0]
  pavement.regeneration: [0]
  pavement.regeneration_degree: [0]

  # Soil
  soil.thickness: [350]
  soil.porosity: [0.43]
  soil.field_capacity: [0.355]
  soil.wilting_point: [0.145]
  soil.k_saturated: [100, 150, 200]
  soil.k_slope: [10]
  soil.suction_head: [50]

  # Storage
  storage.thickness: [370]
  storage.void_fraction: [0.75]
  storage.k_saturated: [0]
  storage.clog_factor: [0]

  # Surface
  surface.thickness: [300]
  surface.void_fraction: [0.2]
  surface.roughness: [0.1]
  surface.slope: [0]

calibration_mode:
  save_rain_events: True

metrics: ['nse_inflow', 'nse_outflow'
          , 'volume_inflow_sim', 'volume_outflow_sim'
          , 'volume_inflow_exp', 'volume_outflow_exp'
          , 'peak_flow', 'time_peak', 'pbias', 'sd', 'ad', 'qd', 'deltaV' ]