experiment:
  file: 'rain_AB.txt'
  headers: ["DateTime", "ml_min_IN_A", "ml_min_OUT_A", "ml_min_IN_B", "ml_min_OUT_B"]
  diameter: 20
  inflow: 'ml_min_IN_A'
  outflow: 'ml_min_OUT_A'


simulation:
  file: 'sgs_valec_01_jp.inp'
  headers: ['DateTime', 'ElapsedTimeHours'
                                    , 'TotalInflow_mm/hr', 'TotalEvap_mm/hr'
                                    , 'SurfaceInfill_mm/hr', 'PavementPerc_mm/hr'
                                    , 'SoilPerc_mm/hr', 'StorageExfil_mm/hr'
                                    , 'SurfaceRunoff_mm/hr', 'DrainOutflow_mm/hr'
                                    , 'SurfaceLevel_mm', 'PavementLevel_mm'
                                    , 'SoilMoistureContent', 'StorageLevel_mm']

  inflow_mm_hr: 'TotalInflow_mm/hr'      
  outflow_mm_hr: 'StorageExfil_mm/hr'  

  inflow_ml_min: 'TotalInflow_ml/min' # Names for internal use (?)
  outflow_ml_min: 'StorageExfil_ml/min' 
   
param_grid:
  soil.porosity: [0.45, 0.5]
  soil.field_capacity: [0.15, 0.2]
  soil.k_saturated: [60]
  soil.k_slope: [40]
  soil.suction_head: [2]
  surface.void_fraction: [0.025]
  storage.void_fraction: [0.3]
  storage.clog_factor: [0]


