name: lid
channels:
  - defaults
dependencies:
  - attrs=19.2.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.8.28
  - certifi=2019.9.11
  - colorama=0.4.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - notebook=6.0.1
  - numpy=1.16.5
  - numpy-base=1.16.5
  - openssl=1.1.1d
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pickleshare=0.7.5
  - pip=19.2.3
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pywin32=223
  - pywinpty=0.5.5
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.4.0
  - sip=4.19.8
  - sqlite=3.30.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=4.3.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - nlopt==2.6.1
    - pyqt5-sip==12.7.0
    - pyswmm==0.5.2
    - pyyaml==5.1.2
    - six==1.12.0